### ISSUE TITLE
Add functionality to filter based on whether the repo's CITATION.cff has seen multiple updates

### ISSUE THREAD

**Issue by jspaaks** [cffbots/filtering#10]
(Spawned from #1)

**Comment by abelsiqueira** [comment]
This could be a sorting criterion, instead of a filter.

**Comment by fdiblen** [comment]
We can use https://octokit.github.io/rest.js/v18#repos-list-commits to list commits to change CITATION.cff.
One should use  `path` parameter to point to CITATION.cff. If there are more than 1 commits, that means the developers updated the file.

**Comment by abelsiqueira** [comment]
Merged
