### ISSUE TITLE
decide on language

### ISSUE THREAD

**Issue by jspaaks** [cffbots/filtering#12]
- some of the filters would need to talk to the github API, so probably something from this list: https://docs.github.com/en/rest/overview/libraries would be convenient
- Python is probably convenient for combining with cffconvert validator
- node would be good (but maybe not necesssary per se) if we want to run this in a scheduled GitHub Action workflow, for example if we're interested in collecting statistics over time.

**Comment by jspaaks** [comment]
Does it need to be one language? If necessary, we can dump to a JSON file and bridge the language gap, right?

**Comment by jspaaks** [comment]
We decided to use Node.js JavaScript with octokit library for making requests to the GitHub API

**Comment by fdiblen** [comment]
Octokit repo: https://github.com/octokit/octokit.js
