### ISSUE TITLE
Write the text of the pull request

### ISSUE THREAD

**Issue by jspaaks** [cffbots/filtering#14]
Maybe things to include are:

- who is making the issue / where we are coming from?
- what to do next?
- what if they don't feel like following up / accepting our suggestion?
- where can they leave feedback?
- include notification/mention of other team members. How can we get a clean list of notifications, only the ones that have something to do with these PRs/issues? (Maybe by including @nlescgt?) 

Might be that certain repos prefer that issues are created in a certain way, using certain formats. (How) do we try to stick to those rules?

**Comment by fdiblen** [comment]
Also come up with a text for external repositories (outside NLeSC).

**Comment by jspaaks** [comment]
I'm wondering if it isn't better to make PRs directly, since we don't know when/if people will respond to our issue, and we're not confident we'll read it/see the notification.

**Comment by jspaaks** [comment]
PR was merged, clsoing
