### ISSUE TITLE
decide on input/output for the filters

### ISSUE THREAD

**Issue by jspaaks** [cffbots/filtering#15]
What will the filters of #1 pass to each other, how will they do it?

**Comment by jspaaks** [comment]
If we're interesting in collecting metrics, we may need something like an array of objects, like:

```json
[{
   "url": "https://github.com/theorg/therepo",
   "has_cff": true,
   "accepts_prs": true,
   "cffversion": "1.0.3",
   "uses_workflows": true
}, {
   "url": "https://github.com/theorg/therepo2",
   "has_cff": false,
   "accepts_prs": true,
   "cffversion": "1.2.0",
   "uses_workflows": false
}]
```

**Comment by jspaaks** [comment]
We decided to use the array of objects or a table, with each filtering function adding one or more keys or columns to each object in the array.

We decided against pure filters that make the initiali set of repository names smaller

**Comment by fdiblen** [comment]
Octokit repo: https://github.com/octokit/octokit.js
