### ISSUE TITLE
Add functionality to filter on valid `CITATION.cff`

### ISSUE THREAD

**Issue by jspaaks** [cffbots/filtering#4]
(Spawned from #1)

Choosing cffconvert as the validator probably affects #12. Alternatively, you could pick a language that is able to run docker commands or shell commands.

**Comment by fdiblen** [comment]
Notes from @fdiblen and @abelsiqueira

1. make sure cffconvert is installed locally
1. to validate, run: `cffconvert --validate --url https://github.com/<org>/<repo>`
  - to run cffvonvert in javascript use exec (see below)
  - store the validity (boolean) for each repo

Exec example taken from  https://stackabuse.com/executing-shell-commands-with-node-js/
```js
const { exec } = require("child_process");

exec("ls -la", (error, stdout, stderr) => {
    if (error) {
        console.log(`error: ${error.message}`);
        return;
    }
    if (stderr) {
        console.log(`stderr: ${stderr}`);
        return;
    }
    console.log(`stdout: ${stdout}`);
});
```

**Comment by fdiblen** [comment]
Jurriaan suggested to use Docker instead of cffconvert as it will be closer to the github action.

**Comment by jspaaks** [comment]
Also, specify the branch

**Comment by jspaaks** [comment]
PR was merged, closing this one
