### ISSUE TITLE
Add functionality to filter on whether the repo already uses workflows

### ISSUE THREAD

**Issue by jspaaks** [cffbots/filtering#5]
(Spawned from #1)

**Comment by fdiblen** [comment]
The alternative would be checking `.github/workflows` folder to see if there are any yaml files.

**Comment by fdiblen** [comment]
> 

We decided to use this method.

**Comment by fdiblen** [comment]
> we can use https://octokit.github.io/rest.js/v18#actions-list-repo-workflows to check if the repo has any workflows.

We decided to use this method.

**Comment by jspaaks** [comment]
PR was merged, closing
